# https://taskfile.dev

version: "3"

tasks:
  docker-release:
    vars:
      VERSION: v1.16.0
      DOCKER_TAG_PREFIX: europe-west1-docker.pkg.dev/slashid-tools/docker
      PLATFORMS: linux/amd64 #,linux/arm64
    cmds:
      - |
        docker buildx build --push \
        --platform {{.PLATFORMS}} \
        -t {{.DOCKER_TAG_PREFIX}}/algolia/docsearch-scraper-base:{{.VERSION}} \
        -t {{.DOCKER_TAG_PREFIX}}/algolia/docsearch-scraper-base:latest \
        -f ./scraper/dev/docker/Dockerfile.base \
        .
      - |
        docker buildx build --push \
        --platform {{.PLATFORMS}} \
        -t {{.DOCKER_TAG_PREFIX}}/algolia/docsearch-scraper:{{.VERSION}} \
        -t {{.DOCKER_TAG_PREFIX}}/algolia/docsearch-scraper:latest \
        -f ./scraper/dev/docker/Dockerfile \
        .
