#!/usr/bin/env bash
cd "$(dirname "$BASH_SOURCE")"
repo_root=$(pwd)

api_key="apiKey"
app_id="appID"
config_name="__test"
container_name="test"
prefix="prefix_"
config=$(cat "${repo_root}/configs/${config_name}.json")
mount_path="${repo_root}/src"

docker stop $container_name 2>/dev/null
docker rm $container_name 2>/dev/null

docker run \
    -e APPLICATION_ID=$app_id \
    -e API_KEY=$api_key \
    -e INDEX_PREFIX=$prefix \
    -e CONFIG="$config" \
    -v "${mount_path}:/root/src" \
    --name $container_name \
    -t algolia/documentation-scrapper-dev \
    /root/test


