FROM ubuntu:14.04
MAINTAINER Algolia <documentationsearch@algolia.com>

# Install selenium
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN useradd -d /home/seleuser -m seleuser
RUN chown -R seleuser /home/seleuser
RUN chgrp -R seleuser /home/seleuser

RUN apt-get -y update
RUN apt-get install -y -q software-properties-common wget
RUN add-apt-repository -y ppa:chris-lea/node.js
RUN add-apt-repository -y ppa:webupd8team/java
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && apt-get update -y && apt-get install -y -q \
  firefox \
  oracle-java8-installer \
  nodejs \
  x11vnc \
  xvfb

RUN npm install -g \
  selenium-standalone@3.0.2 \
  && selenium-standalone install

# Install DocSearch dependencies
RUN apt-get update -y && apt-get install -y \
      curl        \
      fontconfig  \
      libffi-dev  \
      libssl-dev  \
      libxml2-dev \
      libxslt-dev \
      python-dev  \
      python-pip


COPY requirements.txt /root/
COPY scraper/dev/docker/bin/setup_python.sh /root/

RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-linux64.tar.gz
RUN tar xvf geckodriver-v0.9.0-linux64.tar.gz
RUN mv geckodriver wires; cp wires /usr/bin/

# Put everything in /root
WORKDIR /root

