FROM algolia/base-docsearch-scraper
MAINTAINER Algolia <documentationsearch@algolia.com>

WORKDIR /root

# Copy DocSearch files
COPY . .
RUN touch .env
ENTRYPOINT ["pipenv", "run", "./docsearch", "test"]
