FROM algolia/base-docsearch-scraper
MAINTAINER Algolia <documentationsearch@algolia.com>

WORKDIR /root

# Copy DocSearch files
COPY . .
RUN sudo PIPENV_HIDE_EMOJIS=1
ENTRYPOINT ["sudo", "pipenv", "run", "./docsearch", "test"]
