# Dev version of the Dockerfile
# - Includes test library
# - Do not COPY ./src
# - Do not define an ENTRYPOINT

FROM algolia/base-documentation-scrapper
MAINTAINER Algolia <documentationsearch@algolia.com>

RUN pip2 install pytest

# Copy DocSearch files
COPY scraper/dev/docker/bin/run /root/
COPY scraper/dev/docker/bin/check_js_render.py /root/
COPY scraper/dev/docker/bin/test /root/
RUN chmod +x /root/test
RUN chmod +x /root/run
