#!/bin/bash

python /root/check_js_render.py

if [ "$?" -eq 0 ]
then
  node /root/server.js 2>&1 &

  while ! nc -z localhost 8090; do
    sleep 1
    ((c++)) && ((c==10)) && echo "PhantomJS has not started" && break
  done
fi

python /root/src/index.py 2>&1
