#!/bin/bash

cd /tmp
mkdir docsearch_deploy
cd docsearch_deploy

if [ $# -eq 0 ]; then
    git clone --depth 1 --branch master git@github.com:algolia/documentation-scraper.git scraper
else
    cp -r /Users/maxiloc/www/docsearch-scraper . && mv docsearch-scraper scraper
fi

cd /tmp/docsearch_deploy/scraper/deployer/
git clone --depth 1 --branch master git@github.com:algolia/docsearch-configs.git public
git clone --depth 1 --branch master git@github.com:algolia/docsearch-configs-private.git private

cd /tmp/docsearch_deploy/scraper
python -m scraper.deployer.index

#rm -rf /tmp/docsearch_deploy
