#!/bin/bash

PROJECT_ROOT=$PWD
cd /tmp

git clone --depth 1 --branch master git@github.com:algolia/docsearch-configs.git docsearch-configs
git clone --depth 1 --branch master git@github.com:algolia/docsearch-configs-private.git docsearch-configs-private

cd $PROJECT_ROOT

python -m deployer.src.index $@

rm -rf /tmp/docsearch-configs
rm -rf /tmp/docsearch-configs-private