#!/bin/bash

echo "$CONFIG" | jq ".deployKey" -r > ~/id_rsa.github
mkdir ~/.ssh
cat << EOF > ~/.ssh/config
host github.com
 HostName github.com
 IdentityFile ~/id_rsa.github
 User git
EOF
chmod 400 ~/id_rsa.github
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

git clone git@github.com:algolia/documentation-scraper.git
cp -r documentation-scraper/configs .
cd checker && node index.js